phrase= "Don't Panic!"
plist= list (phrase)
print(phrase)
print(plist)
print(plist[0])
plist.pop()
plist.pop()
plist.pop()
plist.pop()
plist.pop()
plist.remove('D')
plist.insert(4,'a')
plist.insert(5,'p')
plist.pop()
plist.pop()
plist.remove("'")
plist.insert(2, " ")

new_phrase = ''.join(plist)
print(plist)
print(new_phrase)
